# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib M.ini _M_ini_rcpp_mini_reader
#' @importFrom Rcpp evalCpp
rcpp_mini_reader <- function(filename) {
    .Call('_M_ini_rcpp_mini_reader', PACKAGE = 'M.ini', filename)
}

